# Generated by Django 4.2.5 on 2023-11-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_personcei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth_place',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='personcei',
            name='birth_place',
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='section',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sexe',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_date'), name='unique_name'),
        ),
    ]
