# Generated by Django 4.2.5 on 2023-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_birth_place_person_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='on_cei',
            field=models.BooleanField(default=False),
        ),
    ]
