# Generated by Django 4.2.5 on 2023-11-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_person_on_cei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='on_cei',
            new_name='is_on_cei',
        ),
    ]
